"""
Бот может конвертировать субтитры формата .ass в .srt 
удаляя лишнее и выделяя надписи
"""

from datetime import datetime
import io
import re
from aiogram import Router, Bot
from aiogram.types import Message, FSInputFile
from aiogram.filters import CommandObject, Command
from asuna_bot.config import CONFIG
from asuna_bot.filters.admins import AdminFilter, AllowedUserFilter
from pprint import pprint
from asuna_bot.filters.chat_type import ChatTypeFilter
from asuna_bot.db.mongo import mongo

convert_router = Router()
convert_router.message.filter(AllowedUserFilter(), Command("srt"))


@convert_router.message()
async def ass_to_srt(msg: Message):
    document = msg.reply_to_message.document
    file_name = msg.reply_to_message.document.file_name
    bot = Bot(token=CONFIG.bot.token)
    file = await bot.download(document, file_name)


    with open(file_name, 'r', encoding="utf-8") as f:
        lines = f.readlines()
    
    # remove everything but Dialogue
    lines = [l for l in lines if l.startswith('Dialogue: ')]

    # split the file into events
    events = ''.join(lines).strip().split('Dialogue: ')

    # extract the relevant information from each event
    
    srt_events = []
    i = 1
    while i < len(events[1:]):
        event = events[i]
        elements = event.split(',')
        start = elements[1].replace(".", ",")
        end = elements[2].replace(".", ",")
        effect = elements[8]
        
        # Highlight signs
        if not effect: 
            text = ','.join(elements[9:]).strip().replace("\\N", "")
        else:
            text = "[" + ','.join(elements[9:]).strip().replace("\\N", "") + "]"
        
        # remove "{ }" symbols and everything between them
        text = re.sub(r'{.*?}', '', text)
        
        # check if the end time of the current line is greater than the start time of the next line
        while i < len(events[1:]) - 1:
            next_event = events[i + 1]
            next_elements = next_event.split(',')
            next_start = next_elements[1].replace(".", ",")
            if end > next_start:
                text += ' \n—' + ''.join(next_elements[9:]).strip()
                text = re.sub(r'{.*?}', '', text)
                end = next_elements[2].replace(".", ",")
                i += 1
            else:
                break
        
        srt_events.append((start, end, text))
        i += 1

    todays_datetime = datetime.today().strftime('%H:%M:%S %B %d, %Y')

    # write the SRT file
    srt_text = '\n'.join([f'{i}\n{start}0 --> {end}0\n{text}\n' for i, (start, end, text) in enumerate(srt_events, 2)])
    asuna_str = f"1\n0:00:00,00 --> 0:00:00,00\nGenerated by Asuna Bot at {todays_datetime}\n\n"
    srt_file_name = file_name.replace('.ass', '.srt')
    with open(srt_file_name, 'w', encoding="utf-8") as f:
        f.write(asuna_str)
        f.write(srt_text)
        
    
    f = FSInputFile(srt_file_name)
    # send the SRT file back to the user
    await msg.answer_document(f, caption=srt_file_name)